### PR TITLE
Allow spaces in file paths when parsing change between revs

### PR DESCRIPTION
**Pull request by joshuamiller01**
If BM encounters a change that includes a file path with a space, it breaks.  This changes the regex which maps a change in a given repository type to capture any character rather than only non whitespace.  I can't find any other aspect of the parsing which depends on spaces, so I think this'll work.

### CODE REVIEW

**Comment by jaymzh** [comment]
This needs tests. Also, existing tests are failing.

**Comment by joshuamiller01** [comment]
It's techdebt day and I've finally put some time in to this.  For git, `git diff --name-status` to see the changes, something like:

```
git diff -z --name-status  head a790272eb158274ab5b58e4ab5304355b2655c18
T       tests/modules/specs/httpd-2.4-2/profiles.json
T       tests/repos/drpm/tour-4-4.noarch.rpm
T       tests/repos/drpm/tour-5-0.noarch.rpm
T       tests/repos/drpm/tour-5-1.noarch.rpm
R100    tox.ini_moved   tox.ini
```

I've dredged through CLI options but nothing feels great:
- `core.quotePath` automatically handled unusual characters, but isn't configurable, and space is not considered unusual. 
- `-z` will null terminate, which seems promising, except it also swallows all of the newlines.  Technically we could iterate over one big string, infer the number of expected fields, break that line into separate entries, and then go from there, but that's super ugly.

The option I'm leaning towards is actually to use the normal field separator, which in this case is a tab.  Of course, a file name could have a tab in it, but that's leagues more clowny than spaces.  
@jaymzh wdyt?

**Comment by jaymzh** [comment]
Nice work @joshuamiller01 

Though I suspect your output is probably a copy-paste error since -z uses null-termination but the the output is not null-terminated :)

So part of me just thinks it should error out if there's more than 2 fields, on a line-type we support, ever. The problem, IMO is not that we don't support it, but that we crash and burn like a pilot who lost too many engines. If we just make it clear to the user what went wrong, I think that's probably a great solution.

But if we do want to do something to support stupid filenames, splitting on tabs is probably the best option. Null-termination, as you point out, means the same delimeter is used for both lines and fields and that is going to be error-prone as hell. new-lines-and-tabs should be far more reliable. It's also demonstrably no worse than what we do now.

I will support either detect-and-error-clearly or separate-via-tabs.

**Comment by joshuamiller01** [comment]
Yea, you caught my copy-pasta, true!

I'm against the detect-and-error-clearly route because we have many, many users who'll be confused, and there's no way to automatically go forward once the problem is introduced.  Even deletion of a file with spaces triggers it.  It's a pain on the GD side, but that can be largely solved with a point-in-time fixup.  But on the TT side, it'll be a source of breakage for users for literally months in our enviro.

I'll put together the tabs separation shortly!

**Comment by jaymzh** [comment]
Hmmm. That gives me a thought. We might-could-should implement "both"... not both in the sense of configurable... you've convinced me that error route is suboptimal... but in the sense that while in GD it makes sense to be as resilient as possible, in TT it'd be really nice to be able to forcefully throw errors so that PRs that introduce spaces don't make it into the repo. So having BM report back that this case was hit might be super useful.

**Comment by joshuamiller01** [comment]
That's interesting food for thought.  I don't know if BM is a good place for policy, but there's already hooks in TT (`taste-tester impact`) for looking at the changed files and providing some kind of feedback.  I can imagine extending that or in some other way have a policy aspect in TT.

**Comment by joshuamiller01** [comment]
Closing in favor of https://github.com/facebook/between-meals/pull/111

**Pull request closed without merging**
