### PR TITLE
remove need to include Berksfile.lock in git

### PR DESCRIPTION
**Pull request by JaycenH7**
- always run berks install if using berkshelf

### CODE REVIEW

**Comment by jaymzh** [comment]
I don't have enough context on berkshelf (the berk stuff was contributed) - can you give me some context on the difference of install/update (and why it affects Berksfile.lock) ?

**Comment by odcinek** [comment]
lgtm, @JaycenH7 do the CLA thingie before merge

**Comment by jaymzh** [comment]
@odcinek  explained the berks bit to me. :+1:

**Comment by JaycenH7** [comment]
@jaymzh, I have a Jenkins job that runs Grocery Delivery and it uses Berkshelf to resolve dependencies. When Grocery Delivery (Between-Meals) runs `berks update` without a Berksfile.lock I get an error saying I need to run `berks install` to create the lock file. 

Including the Berksfile.lock in my git commits solve this but this should not be necessary and feels messy.

Also, running `berks install` has the same effect as `berks update` if the Berksfile.lock is already created.

**Comment by jaymzh** [comment]
Make sense. Thanks!

**Pull request merged**
